sudo: required
dist: trusty

language: haxe

os:
  - linux
  - osx
  
haxe:
  - "3.2.1"
  - development
  
matrix:
  allow_failures:
    - haxe: development
    
install:
  - haxelib install travix
  - haxelib install buddy
  - haxelib run travix install
  - node -v

script:
  - haxelib run travix neko -D tink_remoting_server
  - haxelib run travix python -D tink_remoting_server
  - haxelib run travix node -D tink_remoting_server
  - haxelib run travix java -D tink_remoting_server
  - haxelib run travix cpp -D tink_remoting_server
  - haxelib run travix cs -D tink_remoting_server
  - haxelib run travix php -D tink_remoting_server
  - haxe server.hxml
  - nekotools server -d bin -h localhost -p 18081 > /dev/null &
  - sleep 1
  # - haxelib run travix neko -D tink_remoting_client
  # - haxelib run travix python -D tink_remoting_client
  - haxelib run travix node -D tink_remoting_client
  # - haxelib run travix flash -D tink_remoting_client
  # - haxelib run travix java -D tink_remoting_client
  # - haxelib run travix cpp -D tink_remoting_client
  # - haxelib run travix cs -D tink_remoting_client
  # - haxelib run travix php -D tink_remoting_client
